name: Test

on:
    # workflow_run:
    #     workflows: ["Docker registry"]
    #     types:
    #     - completed
    # push:
    #   branches: [trunk]
    workflow_dispatch:

env:
  ECR_PRIVACY: ${{ vars.CONTAINER_REGISTRY_PRIVACY }}
  IMAGE_TAG: latest
  ORGANIZATION_NAME: ${{ github.repository_owner }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  ECR_REPOSITORY_EXTENSION: ''
  TESTS_TYPES: "rest" # ["grpc", "cuda", "fpga", ...]

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      ECR_REGISTRY_PRIVATE_URI: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION_NAME }}.amazonaws.com
      ECR_REGISTRY_PUBLIC_URI: public.ecr.aws
    outputs:
      ECR_REPOSITORY_NAME: ${{ steps.get-output.outputs.ECR_REPOSITORY_NAME }}
      ECR_LOGIN_PASSWORD: ${{ steps.get-output.outputs.ECR_LOGIN_PASSWORD }}
      ECR_REGISTRY_URI: ${{ steps.get-output.outputs.ECR_REGISTRY_URI }}
      IMAGE_TAG: ${{ steps.get-output.outputs.IMAGE_TAG }}
      ECR_REPOSITORY_EXTENSION: ${{ steps.get-output.outputs.ECR_REPOSITORY_EXTENSION }}
      TEST_NAMES: ${{ steps.get-tests.outputs.TEST_NAMES }}    
    environment: test

    steps:
      - name: setup AWS CLI
        run: |
          aws --version
          aws configure set aws_access_key_id ${{ vars.AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
          aws configure set region ${{ vars.AWS_REGION_NAME }}

      - name: Get ECR information
        id: get-output
        run: |
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "ECR_REPOSITORY_EXTENSION=$ECR_REPOSITORY_EXTENSION" >> $GITHUB_OUTPUT

          REPOSITORY_NAME=$(basename ${{ github.repository }})

          # TODO: ECR_REPOSITORY_NAME=$(echo $REPOSITORY_NAME-$BRANCH_NAME | tr A-Z a-z)
          ECR_REPOSITORY_NAME=$(echo $REPOSITORY_NAME-trunk | tr A-Z a-z)
          echo "ECR_REPOSITORY_NAME=$ECR_REPOSITORY_NAME" >> $GITHUB_OUTPUT

          if [[ $ECR_PRIVACY == private ]]; then
            echo "ECR_LOGIN_PASSWORD=$(aws ecr get-login-password --region ${{ vars.AWS_REGION_NAME }})" >> $GITHUB_OUTPUT
            ECR_REGISTRY_URI=$ECR_REGISTRY_PRIVATE_URI
          elif [[ $ECR_PRIVACY == public ]]; then
            echo "ECR_LOGIN_PASSWORD=$(aws ecr-public get-login-password --region us-east-1)" >> $GITHUB_OUTPUT
            ECR_REGISTRY_URI=$ECR_REGISTRY_PUBLIC_URI            
          fi

          echo "ECR_REGISTRY_URI=$ECR_REGISTRY_URI" >> $GITHUB_OUTPUT
          echo using docker image::: $ECR_REGISTRY_URI/$ECR_REPOSITORY_NAME$ECR_REPOSITORY_EXTENSION:$IMAGE_TAG

      - name: Checkout
        uses: actions/checkout@v3
      - name: Get tests
        id: get-tests
        run: |
          files=""
          for test_type in $TESTS_TYPES; do
            files+="$(find tests -type f -name "*$test_type*.tftest.hcl" -exec basename {} *.tftest.hcl \;) "
          done

          transformed_string=""
          for file in $files; do
            transformed_string+="{\"test_name\": \"$file\"},"            
          done
          transformed_string=${transformed_string%,} # Remove the trailing comma and close the square brackets

          echo $transformed_string
          echo TEST_NAMES={\"include\":[$transformed_string]} >> $GITHUB_OUTPUT

  test:
    needs: [setup]
    runs-on: ubuntu-latest
    container: 
      image: ${{ needs.setup.outputs.ECR_REGISTRY_URI }}/${{ needs.setup.outputs.ECR_REPOSITORY_NAME}}${{ needs.setup.outputs.ECR_REPOSITORY_EXTENSION }}:${{ needs.setup.outputs.IMAGE_TAG }}
      credentials:
        username: AWS
        password: ${{ needs.setup.outputs.ECR_LOGIN_PASSWORD }}
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.TEST_NAMES) }}
    environment: test

    env:      
      AWS_REGION_NAME: ${{ vars.AWS_REGION_NAME }}
      AWS_PROFILE_NAME: ${{ vars.AWS_PROFILE_NAME }}
      AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
      AWS_ACCESS_KEY: ${{ vars.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      GITHUB_OWNER: ${{ github.repository_owner }}
      GITHUB_TOKEN: ${{ secrets.GH_TERRA_TOKEN }}
      TF_VAR_branch_name: ${{ github.head_ref || github.ref_name }}
      TF_VAR_vpc_id: ${{ vars.VPC_ID }}
      TF_VAR_domain_name: ${{ vars.DOMAIN_NAME }}
      TF_VAR_domain_suffix: ${{ vars.DOMAIN_SUFFIX }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Versions
        run: |
          terraform --version

      - name: Setup AWS CLI
        run: |
          make -f Makefile aws-auth

      - name: Setup Test
        run: |
          make -f Makefile prepare
          terraform init

      - name: Run Test
        run: |
          echo Running ${{ matrix.test_name }}
          ls
          ls tests
          terraform test -filter=tests/${{ matrix.test_name }}

          # exitCode=0
          # files="test1 test2 test3"
          # for file in $files; do
          # exitCodeTest=$(run test here > test_results.txt; echo $?)
          # if [ $exitCodeTest -eq 0  ]; then
          #   echo -e '::group::\033[42mSUCCESSFUL\033[0m Click to view test logs'
          # else
          # exitCode=$exitCodeTest
          #   echo -e '::group::\033[42mFAILURE\033[0m Click to view test logs'
          # fi
          # cat test_results.txt
          # echo "::endgroup::"
          # done
          # exit $exitCode