name: Testtttt

on:
    workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      TEST_NAMES: ${{ steps.get-test.outputs.TEST_NAMES }}
    steps:
      - name: find tests
        id: get-test
        run: |
          echo TEST_NAMES='["rest/Test_1", "grpc/Test_2"]' >> $GITHUB_OUTPUT

  test:
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir_name: ${{ needs.setup.outputs.TEST_NAMES }}

    steps:
      - name: Print
        run: |
          echo ${{ matrix.dir_name }}
        